### ISSUE TITLE
Unable to pull

### ISSUE THREAD

**Issue by acolasialiuliu** [flarum-com/ai-toolkit#2]
Problem 1
    - Root composer.json requires flarum/ai-toolkit *, found flarum/ai-toolkit[dev-main] but it does not match your minimum-stability.

I tried to remove the version number and modify the minimum version limit, but I couldn't pull this item.

Could not find a version of package flarum/ai-toolkit matching your minimum-stability (s  
  table). Require it with an explicit version constraint allowing its desired stability.

**Comment by luceos** [comment]
There's no release yet

**Comment by acolasialiuliu** [comment]
ok

**Comment by luceos** [comment]
Try the development version using

```
composer require blomstra/ai-toolkit:"dev-main"
```

But understand it might still be buggy, a lot.
